// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/port/project_config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/beliaev-aa/notifications/internal/config"
	gomock "github.com/golang/mock/gomock"
)

// MockProjectConfigService is a mock of ProjectConfigService interface.
type MockProjectConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectConfigServiceMockRecorder
}

// MockProjectConfigServiceMockRecorder is the mock recorder for MockProjectConfigService.
type MockProjectConfigServiceMockRecorder struct {
	mock *MockProjectConfigService
}

// NewMockProjectConfigService creates a new mock instance.
func NewMockProjectConfigService(ctrl *gomock.Controller) *MockProjectConfigService {
	mock := &MockProjectConfigService{ctrl: ctrl}
	mock.recorder = &MockProjectConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectConfigService) EXPECT() *MockProjectConfigServiceMockRecorder {
	return m.recorder
}

// GetAllowedChannels mocks base method.
func (m *MockProjectConfigService) GetAllowedChannels(projectName string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedChannels", projectName)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedChannels indicates an expected call of GetAllowedChannels.
func (mr *MockProjectConfigServiceMockRecorder) GetAllowedChannels(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedChannels", reflect.TypeOf((*MockProjectConfigService)(nil).GetAllowedChannels), projectName)
}

// GetProjectConfig mocks base method.
func (m *MockProjectConfigService) GetProjectConfig(projectName string) (*config.ProjectConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectConfig", projectName)
	ret0, _ := ret[0].(*config.ProjectConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetProjectConfig indicates an expected call of GetProjectConfig.
func (mr *MockProjectConfigServiceMockRecorder) GetProjectConfig(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectConfig", reflect.TypeOf((*MockProjectConfigService)(nil).GetProjectConfig), projectName)
}

// GetSendDraftNotification mocks base method.
func (m *MockProjectConfigService) GetSendDraftNotification(projectName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSendDraftNotification", projectName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetSendDraftNotification indicates an expected call of GetSendDraftNotification.
func (mr *MockProjectConfigServiceMockRecorder) GetSendDraftNotification(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSendDraftNotification", reflect.TypeOf((*MockProjectConfigService)(nil).GetSendDraftNotification), projectName)
}

// GetTelegramChatID mocks base method.
func (m *MockProjectConfigService) GetTelegramChatID(projectName string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramChatID", projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTelegramChatID indicates an expected call of GetTelegramChatID.
func (mr *MockProjectConfigServiceMockRecorder) GetTelegramChatID(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramChatID", reflect.TypeOf((*MockProjectConfigService)(nil).GetTelegramChatID), projectName)
}

// GetVKTeamsChatID mocks base method.
func (m *MockProjectConfigService) GetVKTeamsChatID(projectName string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVKTeamsChatID", projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetVKTeamsChatID indicates an expected call of GetVKTeamsChatID.
func (mr *MockProjectConfigServiceMockRecorder) GetVKTeamsChatID(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVKTeamsChatID", reflect.TypeOf((*MockProjectConfigService)(nil).GetVKTeamsChatID), projectName)
}

// IsProjectAllowed mocks base method.
func (m *MockProjectConfigService) IsProjectAllowed(projectName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProjectAllowed", projectName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProjectAllowed indicates an expected call of IsProjectAllowed.
func (mr *MockProjectConfigServiceMockRecorder) IsProjectAllowed(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProjectAllowed", reflect.TypeOf((*MockProjectConfigService)(nil).IsProjectAllowed), projectName)
}
