// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/port/notification.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	port "github.com/beliaev-aa/notifications/internal/domain/port"
	gomock "github.com/golang/mock/gomock"
)

// MockNotificationChannel is a mock of NotificationChannel interface.
type MockNotificationChannel struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationChannelMockRecorder
}

// MockNotificationChannelMockRecorder is the mock recorder for MockNotificationChannel.
type MockNotificationChannelMockRecorder struct {
	mock *MockNotificationChannel
}

// NewMockNotificationChannel creates a new mock instance.
func NewMockNotificationChannel(ctrl *gomock.Controller) *MockNotificationChannel {
	mock := &MockNotificationChannel{ctrl: ctrl}
	mock.recorder = &MockNotificationChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationChannel) EXPECT() *MockNotificationChannelMockRecorder {
	return m.recorder
}

// Channel mocks base method.
func (m *MockNotificationChannel) Channel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channel")
	ret0, _ := ret[0].(string)
	return ret0
}

// Channel indicates an expected call of Channel.
func (mr *MockNotificationChannelMockRecorder) Channel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channel", reflect.TypeOf((*MockNotificationChannel)(nil).Channel))
}

// Send mocks base method.
func (m *MockNotificationChannel) Send(chatID, formattedMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", chatID, formattedMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationChannelMockRecorder) Send(chatID, formattedMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationChannel)(nil).Send), chatID, formattedMessage)
}

// MockNotificationSender is a mock of NotificationSender interface.
type MockNotificationSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderMockRecorder
}

// MockNotificationSenderMockRecorder is the mock recorder for MockNotificationSender.
type MockNotificationSenderMockRecorder struct {
	mock *MockNotificationSender
}

// NewMockNotificationSender creates a new mock instance.
func NewMockNotificationSender(ctrl *gomock.Controller) *MockNotificationSender {
	mock := &MockNotificationSender{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSender) EXPECT() *MockNotificationSenderMockRecorder {
	return m.recorder
}

// RegisterChannel mocks base method.
func (m *MockNotificationSender) RegisterChannel(channel port.NotificationChannel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterChannel", channel)
}

// RegisterChannel indicates an expected call of RegisterChannel.
func (mr *MockNotificationSenderMockRecorder) RegisterChannel(channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChannel", reflect.TypeOf((*MockNotificationSender)(nil).RegisterChannel), channel)
}

// Send mocks base method.
func (m *MockNotificationSender) Send(channel, chatID, formattedMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", channel, chatID, formattedMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationSenderMockRecorder) Send(channel, chatID, formattedMessage interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationSender)(nil).Send), channel, chatID, formattedMessage)
}
