// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/port/parser/youtrack.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	parser "github.com/beliaev-aa/notifications/internal/domain/port/parser"
	gomock "github.com/golang/mock/gomock"
)

// MockYoutrackParser is a mock of YoutrackParser interface.
type MockYoutrackParser struct {
	ctrl     *gomock.Controller
	recorder *MockYoutrackParserMockRecorder
}

// MockYoutrackParserMockRecorder is the mock recorder for MockYoutrackParser.
type MockYoutrackParserMockRecorder struct {
	mock *MockYoutrackParser
}

// NewMockYoutrackParser creates a new mock instance.
func NewMockYoutrackParser(ctrl *gomock.Controller) *MockYoutrackParser {
	mock := &MockYoutrackParser{ctrl: ctrl}
	mock.recorder = &MockYoutrackParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYoutrackParser) EXPECT() *MockYoutrackParserMockRecorder {
	return m.recorder
}

// GetAllowedChannels mocks base method.
func (m *MockYoutrackParser) GetAllowedChannels(payload *parser.YoutrackWebhookPayload) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedChannels", payload)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetAllowedChannels indicates an expected call of GetAllowedChannels.
func (mr *MockYoutrackParserMockRecorder) GetAllowedChannels(payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedChannels", reflect.TypeOf((*MockYoutrackParser)(nil).GetAllowedChannels), payload)
}

// GetSendDraftNotification mocks base method.
func (m *MockYoutrackParser) GetSendDraftNotification(projectName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSendDraftNotification", projectName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetSendDraftNotification indicates an expected call of GetSendDraftNotification.
func (mr *MockYoutrackParserMockRecorder) GetSendDraftNotification(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSendDraftNotification", reflect.TypeOf((*MockYoutrackParser)(nil).GetSendDraftNotification), projectName)
}

// GetTelegramChatID mocks base method.
func (m *MockYoutrackParser) GetTelegramChatID(projectName string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTelegramChatID", projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTelegramChatID indicates an expected call of GetTelegramChatID.
func (mr *MockYoutrackParserMockRecorder) GetTelegramChatID(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTelegramChatID", reflect.TypeOf((*MockYoutrackParser)(nil).GetTelegramChatID), projectName)
}

// GetVKTeamsChatID mocks base method.
func (m *MockYoutrackParser) GetVKTeamsChatID(projectName string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVKTeamsChatID", projectName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetVKTeamsChatID indicates an expected call of GetVKTeamsChatID.
func (mr *MockYoutrackParserMockRecorder) GetVKTeamsChatID(projectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVKTeamsChatID", reflect.TypeOf((*MockYoutrackParser)(nil).GetVKTeamsChatID), projectName)
}

// NewFormatter mocks base method.
func (m *MockYoutrackParser) NewFormatter() parser.YoutrackFormatter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFormatter")
	ret0, _ := ret[0].(parser.YoutrackFormatter)
	return ret0
}

// NewFormatter indicates an expected call of NewFormatter.
func (mr *MockYoutrackParserMockRecorder) NewFormatter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFormatter", reflect.TypeOf((*MockYoutrackParser)(nil).NewFormatter))
}

// ParseJSON mocks base method.
func (m *MockYoutrackParser) ParseJSON(payload []byte) (*parser.YoutrackWebhookPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseJSON", payload)
	ret0, _ := ret[0].(*parser.YoutrackWebhookPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseJSON indicates an expected call of ParseJSON.
func (mr *MockYoutrackParserMockRecorder) ParseJSON(payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseJSON", reflect.TypeOf((*MockYoutrackParser)(nil).ParseJSON), payload)
}

// MockYoutrackFormatter is a mock of YoutrackFormatter interface.
type MockYoutrackFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockYoutrackFormatterMockRecorder
}

// MockYoutrackFormatterMockRecorder is the mock recorder for MockYoutrackFormatter.
type MockYoutrackFormatterMockRecorder struct {
	mock *MockYoutrackFormatter
}

// NewMockYoutrackFormatter creates a new mock instance.
func NewMockYoutrackFormatter(ctrl *gomock.Controller) *MockYoutrackFormatter {
	mock := &MockYoutrackFormatter{ctrl: ctrl}
	mock.recorder = &MockYoutrackFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYoutrackFormatter) EXPECT() *MockYoutrackFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockYoutrackFormatter) Format(payload *parser.YoutrackWebhookPayload, channel string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", payload, channel)
	ret0, _ := ret[0].(string)
	return ret0
}

// Format indicates an expected call of Format.
func (mr *MockYoutrackFormatterMockRecorder) Format(payload, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockYoutrackFormatter)(nil).Format), payload, channel)
}

// RegisterChannelFormatter mocks base method.
func (m *MockYoutrackFormatter) RegisterChannelFormatter(channel string, formatter func(*parser.YoutrackWebhookPayload) string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterChannelFormatter", channel, formatter)
}

// RegisterChannelFormatter indicates an expected call of RegisterChannelFormatter.
func (mr *MockYoutrackFormatterMockRecorder) RegisterChannelFormatter(channel, formatter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChannelFormatter", reflect.TypeOf((*MockYoutrackFormatter)(nil).RegisterChannelFormatter), channel, formatter)
}
